### ISSUE TITLE
bug: watch dog timing out on goerli

### ISSUE THREAD

**Issue by ahhda** [cowprotocol/watch-tower#85]
### Problem
Goerli WatchTower deployment is crashing

```
2023-10-04T07:31:09.006Z ERROR chainContext:runBlockWatcher:5: Watchdog timeout

2023-10-04T07:30:40.056Z ERROR checkForAndPlaceOrder:_pollLegacy:5:2.9@9806576: Error on CALL to getTradeableOrderWithSignature. Simulate: https://dashboard.tenderly.co/gp-v2/watch-tower-prod/simulator/new?network=5&contractAddress=0xfdaFc9d1902f4e0b84f65F49f244b32b31013b74&rawFunctionInput=0x26e0a1960000000000000000000000008654d1136f2a760ba3e1c9e131cb9ad217921b52000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000002400000000000000000000000000000000000000000000000000000000000000260000000000000000000000000910d00a310f7dc5b29fe73458f47f519be547d3d000000000000000000000000000000000000000000000000000000189e3b096000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000140000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d600000000000000000000000091056d4a53e1faa1a84306d4deaec71085394bc80000000000000000000000008654d1136f2a760ba3e1c9e131cb9ad217921b5200000000000000000000000000000000000000000000000000b1a2bc2ec500000000000000000000000000000000000000000000000000063fa67b061775f0c90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000007080000000000000000000000000000000000000000000000000000000000000000506960793899dbd9225c61c44bd44927462151c82dec95315cf937f6b95ef21f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

2023-10-04T07:30:40.056Z ERROR checkForAndPlaceOrder:_handleGetTradableOrderCall:5:2.9@9806576: checkForAndPlaceOrder:_handleGetTradableOrderCall:5:2.9@9806576 Unexpected error LowLevelError: low-level call failed     at _pollLegacy (/usr/src/app/dist/src/domain/checkForAndPlaceOrder.js:340:19)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async _processConditionalOrder (/usr/src/app/dist/src/domain/checkForAndPlaceOrder.js:141:26)     at async checkForAndPlaceOrder (/usr/src/app/dist/src/domain/checkForAndPlaceOrder.js:70:32)     at async processBlock (/usr/src/app/dist/src/domain/chainContext.js:213:20)     at async JsonRpcProvider.<anonymous> (/usr/src/app/dist/src/domain/chainContext.js:155:21) {   data: '0xf3ec7a9f' }
```

### Impact
Causing restarts as well as alerts for on call

### To reproduce
Check for logs in `goerli-watch-tower` deployment

### Expected behaviour
The service should not crash

### Screenshots/logs
Search for "Watchdog timeout" in ES
Example, https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/Uk7oi

### Tenderly watch-tower version/commit hash
- `v1.0.1-rc.0`

**Comment by mfw78** [comment]
On investigating this, the watch-tower is working as prescribed, though the tolerances for the chain monitoring may need to be revised dependent on the underlying chain's stability.

Goerli commonly skips slots, leading to timeout events.

For example observe the following blocks:
* [9810741](https://goerli.etherscan.io/block/9810741)
* [9810742](https://goerli.etherscan.io/block/9810742)

There is a 36 second delay between these blocks, and the watch-dog that monitors the chain (to detect RPC issues / chain issues) has a configured 30 second timeout. There's no easy "fix" for this, as it's not a watch-tower problem, and it's doing it's job alerting when the underlying infrastructure is failing / causing issues.

Having said this, we can enable some better "tolerance" mechanisms. I'd suggest that we make the watch dog timeout configurable and set this according to the underlying chain. For goerli, when browsing through [slots on prater](https://prater.beaconcha.in/slots), it's common to observe 5 slots missing consecutively (1 min at a blocktime of 12s). Therefore for goerli, we could maybe widen the timeout to 2 mins to be on the conservative side.
